services:
  db:
    image: mysql:8.0
    container_name: n8n-storage
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${PORT_MYSQL}"
    volumes:
      - n8n-storage:/var/lib/mysql
        
  frontend:
    build: ./app
    ports:
      - "${PORT_FRONTEND}"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./n8n
    ports:
      - "${PORT_BACKEND}"
    networks:
      - app-network
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./n8n:/home/node/.n8n

networks:
  app-network:
    driver: bridge

volumes:
  n8n-storage: